# Generated by Django 2.2.15 on 2022-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='best_trick',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
